import { ShieldCheck } from "lucide-react";
import LegalDocument from "@/components/common/LegalDocument";

export const metadata = { title: "Privacy Policy · Owner Rewards" };

export default function Page() {
  return (
    <LegalDocument
      icon={ShieldCheck}
      eyebrow="Legal"
      title="Privacy Policy"
      description="How we collect, use, and protect your personal information."
      lastUpdated="August 1, 2026"
      sections={[
        {
          id: "collect",
          title: "1. Information we collect",
          body: "We collect personal information you provide (name, contact details, account preferences) and information generated by your use of the service (redemption history, device data, and site interactions).",
        },
        {
          id: "use",
          title: "2. How we use your information",
          body: "We use your information to provide the service, process redemptions, communicate with you, and improve your experience. We do not sell your personal information.",
        },
        {
          id: "sharing",
          title: "3. Sharing with third parties",
          body: "We share limited information with service providers who help us operate the service (e.g., gift card fulfillment partners, banking providers). These providers are bound by confidentiality obligations.",
        },
        {
          id: "cookies",
          title: "4. Cookies and analytics",
          body: "We use cookies and similar technologies to remember your preferences and understand usage. You can control cookies through your browser settings.",
        },
        {
          id: "security",
          title: "5. Security",
          body: "We use industry-standard measures to protect your data, including encryption in transit and at rest, access controls, and regular audits. No system is 100% secure — please protect your credentials.",
        },
        {
          id: "rights",
          title: "6. Your rights",
          body: "You may request access, correction, or deletion of your personal information by contacting Owner Services. You may opt out of marketing communications at any time from your Account page.",
        },
        {
          id: "contact",
          title: "7. Contact us",
          body: "Questions about this policy? Email owner-services@example.com or write to Owner Rewards Privacy Office, PO Box 1000, Orlando, FL 32801.",
        },
      ]}
    />
  );
}
